### PR TITLE
Intital scaffolding of app using create-react-app 

### PR DESCRIPTION
**Pull request by JVanderford**

### CODE REVIEW

**Comment by aamato1990** [comment]
@JVanderford I would wrap the App component in a BrowserRouter component, in order to use react-router-dom to create links to other pages in the SPA.  Using Browser Router should eventually allow for server-side rendering of routes as well (for SEO sake), via a separate but analogous router.  We can talk about this more tomorrow, and I'd like to get a branch off this myself.  For now I'm going to approve/merge this to get the ball rolling

**Comment by aamato1990** [comment]
Alas, I don't have write access 👎 

Regardless, I say :shipit:

**Comment by JVanderford** [comment]
Brian, did you mean to merge this up?  I don't have write access so I can't merge.

**Comment by JVanderford** [comment]
@BWortman   I've addressed the port and the rimraf issues.  I'm not sure what issue you're having with npm test, other than there are no tests yet so there is nothing to run.  The test watch runs fine for me, just reports that there are no tests to run.

**Pull request merged**
