### PR TITLE
Feature/move hard coded values

### LINKED ISSUE #18: Moving string constants like ActionTypes and API URL to variable access
Moving the ActionTypes to an actiontypes file so that we don't have magic strings in the actions and reducers, also moving the API string to a config global so that we can more easily handle dev vs prod api access.

### PR DESCRIPTION
**Pull request by JaredVanderford**
Closes #18

### CODE REVIEW

**Comment by aamato1990** [comment]
All functionality maintained, tests pass, lint passes. Was going to do this in my next branch... thanks for taking care of it.

LGTM. :shipit:

**Comment by JaredVanderford** [comment]
@BWortman  did you get that when running the API?  I get that screen when the API is not running,

**Comment by aamato1990** [comment]
@BWortman  just confirmed that when running the API locally and hitting autorenter-react from 127.0.0.1, data does come through.  

It appears that @JaredVanderford also resolved the poor error handling that leads to the fatal error, so now an error message displays properly instead of just crashing... thanks jared :)

**Comment by JaredVanderford** [comment]
@aamato1990  yeah I saw that screen when not running the API.  it seems the Axios Error object doesn't return a response if there is a connection error.  We might want to think about extracting that check so that we don't have to repeat it everywhere, but for now on the one action it should just display the error message.  Took me a bit to figure out because I couldn't find good docs on the Error object from Axios, and just logging the error gave me a nice message about what happened.

**Pull request merged**
